.yarn_job:
  image: node:18-alpine
  before_script:
    - yarn

stages:
  - test

test:
  stage: test
  extends: .yarn_job
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script: yarn workspace ${PACKAGE} jest --ci
  parallel:
    matrix:
      - PACKAGE:
          - "@cat/music"
          - "@cat/utils"
  artifacts:
    expire_in: "7 days"
    reports:
      junit: "**/junit.xml"
      coverage_report:
        coverage_format: cobertura
        path: "**/coverage/cobertura-coverage.xml"

lint:
  stage: test
  extends: .yarn_job
  script: yarn lint

types:
  stage: test
  extends: .yarn_job
  script: yarn types
