name: Pipeline CI

on: ["push"]
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  test:
    uses: ./.github/workflows/node.yml
    with:
      task: test

  lint:
    uses: ./.github/workflows/node.yml
    with:
      task: lint

  types:
    uses: ./.github/workflows/node.yml
    with:
      task: types
